name: Media Card
icon: image
preview: fields
blueprint: block

fields:
  image:
    label: Media / Image
    type: files
    max: 1
    layout: cards
    size: large
    query: site.find("media").files.add(page.files)
    uploads: image
